POST https://www.cnstats.org/e/search/index.php
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
Content-Type: application/x-www-form-urlencoded

keyboard=%E7%94%98%E5%AD%9C%E5%B7%9E&show=title&tempid=1&tbname=news&x=58&y=11