GET http://127.0.0.1:5000/user/info
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzUzOTA5MjEsIm5iZiI6MTU3NTM5MDkyMSwianRpIjoiODExMTQxMTQtZDA2Yi00ZGFmLTgzNDctOTRlN2Q3YTIwMGQxIiwiZXhwIjoxNTc1MzkxODIxLCJpZGVudGl0eSI6ImhmakBrZGlmLmNvbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyIsInVzZXJfY2xhaW1zIjp7ImlkIjo0LCJ1c2VybmFtZSI6ImFjbGRtIiwiZW1haWwiOiJoZmpAa2RpZi5jb20ifX0.NlcsG77qGGhPw13yqueO9APlCS3-IeTOrB3YE1Rtwq4