GET http://127.0.0.1:5000/user/haslogin
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzU0Mzg1OTcsIm5iZiI6MTU3NTQzODU5NywianRpIjoiMDZkOGU3ZGQtNjM4MC00MGJiLTk5NmEtODBmN2ZiMzBiN2YyIiwiZXhwIjoxNTc1NDM5NDk3LCJpZGVudGl0eSI6ImhmakBrZGlmLmNvbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyIsInVzZXJfY2xhaW1zIjp7ImlkIjo0LCJ1c2VybmFtZSI6ImFjbGRtIiwiZW1haWwiOiJoZmpAa2RpZi5jb20ifX0.cB4vODjss1VUxGcu97IJrlm6Vbh5T0vsb4UQmMJwbb0