GET http://127.0.0.1:5000/api/feel/favorite/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzYyMTc2NjUsIm5iZiI6MTU3NjIxNzY2NSwianRpIjoiNDk0NGMyNmMtZjQwNC00YzIzLThiNmItOWQxZTk2YjE2MzI2IiwiaWRlbnRpdHkiOiJhbWlAYWJjLmNvbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyIsInVzZXJfY2xhaW1zIjp7ImlkIjoyLCJ1c2VybmFtZSI6ImFtaSIsImVtYWlsIjoiYW1pQGFiYy5jb20ifX0.8F4RUKtQgquNFmcyYCCWcI3h1EPJIp7YQuTQyTP2mng
