"""empty message

Revision ID: 43695ea713a3
Revises: 
Create Date: 2020-02-08 22:20:09.411341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43695ea713a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=31), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=255), nullable=True),
    sa.Column('job', sa.String(length=255), nullable=True),
    sa.Column('rare', sa.String(length=3), nullable=False),
    sa.Column('melee', sa.String(length=1), nullable=False),
    sa.Column('strength', sa.String(length=1), nullable=False),
    sa.Column('ps', sa.String(length=1), nullable=False),
    sa.Column('research', sa.String(length=1), nullable=False),
    sa.Column('remote', sa.String(length=1), nullable=False),
    sa.Column('speed', sa.String(length=1), nullable=False),
    sa.Column('lucky', sa.String(length=1), nullable=False),
    sa.Column('talk', sa.String(length=1), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store')
    op.drop_table('user')
    op.drop_table('card')
    # ### end Alembic commands ###
