POST http://www.localhost:5000/card/get_cards
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODExNDIzMzIsIm5iZiI6MTU4MTE0MjMzMiwianRpIjoiYTJkZjMzOWQtM2JmOS00MmU2LWE3MmYtZDU2YTUzYzIzMGVjIiwiaWRlbnRpdHkiOiJ7XCJpZFwiOiAxLCBcInVzZXJuYW1lXCI6IFwibGluZGFcIiwgXCJwYXNzd29yZFwiOiBcInBia2RmMjpzaGEyNTY6MTUwMDAwJEtRRVJ3eGpCJGIxMjM0ODE1Mjk3ZTkwNjEzNGQwYmJkNGNhYjllYjUyOWI4ZDI4N2QwZDIxNGM0YjJhYWE1NWMxMWZmNDk0YzlcIn0iLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MiLCJ1c2VyX2NsYWltcyI6eyJpZCI6MSwidXNlcm5hbWUiOiJsaW5kYSIsInBhc3N3b3JkIjoicGJrZGYyOnNoYTI1NjoxNTAwMDAkS1FFUnd4akIkYjEyMzQ4MTUyOTdlOTA2MTM0ZDBiYmQ0Y2FiOWViNTI5YjhkMjg3ZDBkMjE0YzRiMmFhYTU1YzExZmY0OTRjOSJ9fQ.8q0EEbSR3o1dfdIo3XXjSdjOTiuIoRQzhO_SH463Xrs

{
  "count": 10
}