GET http://localhost:5000/card/get_user_store
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODEwMDIzMTksIm5iZiI6MTU4MTAwMjMxOSwianRpIjoiMWMwN2M5OTctMTUxNy00ZjVhLTg3YTEtNDc0YzA1YTdiYWU5IiwiaWRlbnRpdHkiOiJ7XCJpZFwiOiAxLCBcInVzZXJuYW1lXCI6IFwibGluZGFcIiwgXCJwYXNzd29yZFwiOiBcInBia2RmMjpzaGEyNTY6MTUwMDAwJEtRRVJ3eGpCJGIxMjM0ODE1Mjk3ZTkwNjEzNGQwYmJkNGNhYjllYjUyOWI4ZDI4N2QwZDIxNGM0YjJhYWE1NWMxMWZmNDk0YzlcIn0iLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MiLCJ1c2VyX2NsYWltcyI6eyJpZCI6MSwidXNlcm5hbWUiOiJsaW5kYSIsInBhc3N3b3JkIjoicGJrZGYyOnNoYTI1NjoxNTAwMDAkS1FFUnd4akIkYjEyMzQ4MTUyOTdlOTA2MTM0ZDBiYmQ0Y2FiOWViNTI5YjhkMjg3ZDBkMjE0YzRiMmFhYTU1YzExZmY0OTRjOSJ9fQ.YUcNa3ozBq652OY_VSZ6mihvveDVUCWUS3JsMmVjGyU