GET http://127.0.0.1:5000/user_project
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzUzNzg2MTIsIm5iZiI6MTU3NTM3ODYxMiwianRpIjoiNzRiZjQwY2MtOWE2YS00MmJkLTg0NDQtNzA5YjhjYzZlOWU0IiwiZXhwIjoxNTc1Mzc5NTEyLCJpZGVudGl0eSI6ImhmakBrZGlmLmNvbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyIsInVzZXJfY2xhaW1zIjp7ImlkIjo0LCJ1c2VybmFtZSI6ImFjbGRtIiwicGFzc3dvcmQiOiJhYmNhYmNhYmMiLCJlbWFpbCI6ImhmakBrZGlmLmNvbSJ9fQ.dNvr8S52hmKWBWI42wW68XZ1LD_858c_a7DI5BknpLc