GET http://127.0.0.1:5000/project/user
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzU0NDA0MTAsIm5iZiI6MTU3NTQ0MDQxMCwianRpIjoiYTEyODI2NjYtYjZmOC00NTA2LTk0NDAtYWMxM2JmY2Q3MzI2IiwiZXhwIjoxNTc1NDQxMzEwLCJpZGVudGl0eSI6ImxpbmRhQGFiYy5jb20iLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MiLCJ1c2VyX2NsYWltcyI6eyJpZCI6MSwidXNlcm5hbWUiOiJsaW5kYVxuIiwiZW1haWwiOiJsaW5kYUBhYmMuY29tIn19.l8SiddioYWm4pQTOepk9NSBEOA0C9sw1h3BFpWNlBWw